/**
 * /lib/demoTemplates/categories.js
 *
 * One entry per business category. This is the "brain" the fallback system
 * draws from when Gemini is unavailable. Every string may contain
 * placeholders ({{businessName}}, {{city}}, etc.) which renderTemplate()
 * swaps for real business data at render time.
 *
 * `images.heroQuery` and `images.gallery[]` are photo *search descriptions*,
 * not URLs — they stay here so the correct category always gets the
 * correct kind of photo (cafe → cafe interiors, plumber → pipe repairs,
 * etc). The actual photo fetch happens in attachCategoryImages()
 * (/lib/demoTemplates/attachImages.js), which is the only part of this
 * pipeline that talks to the network. This file itself never makes a
 * network call — it's pure data.
 *
 * `images.gallery[]` is in the SAME ORDER as `gallery[]` below, so
 * gallery[i] (the label) always pairs with images.gallery[i] (the photo
 * search term for that exact tile).
 *
 * Keep content premium and specific — no lorem ipsum, no generic filler.
 */

const categories = {
  restaurant: {
    key: "restaurant",
    label: "Restaurant",
    emoji: "🍽️",
    colors: { primary: "#B5482A", accent: "#E8B24D", dark: "#231712" },
    fonts: { display: "Playfair Display", body: "Inter" },
    images: {
      heroQuery: "fine dining restaurant interior warm lighting",
      gallery: [
        "signature plated dish restaurant",
        "private dining room restaurant",
        "chefs table open kitchen",
        "weekend brunch spread restaurant",
        "restaurant bar corner cocktails",
        "dessert menu plating restaurant",
      ],
    },
    hero: {
      headline: "Authentic {{category}} Cuisine, Crafted Daily",
      subheadline:
        "{{businessName}} brings the flavors of {{city}} to your table — fresh ingredients, timeless recipes, unforgettable evenings.",
      ctaPrimary: "Reserve a Table",
      ctaSecondary: "View Menu",
    },
    about: {
      title: "Our Story",
      body: "{{businessName}} has been serving {{city}} with dishes made from scratch, sourced locally and plated with care. Every visit is a chance to slow down and taste something real.",
    },
    services: [
      { title: "Breakfast", description: "Start the day with fresh, hearty morning favorites.", icon: "Coffee" },
      { title: "Lunch", description: "Quick, satisfying plates for the midday rush.", icon: "UtensilsCrossed" },
      { title: "Dinner", description: "A relaxed evening menu built for sharing.", icon: "Soup" },
      { title: "Takeaway", description: "Your favorites, packed fresh for the road.", icon: "ShoppingBag" },
    ],
    features: [
      { title: "Locally Sourced", description: "Ingredients from trusted local farms and markets." },
      { title: "Chef-Led Kitchen", description: "Every dish is overseen by our head chef." },
      { title: "Warm Ambience", description: "A space designed for real conversations." },
      { title: "Private Events", description: "Book the whole restaurant for celebrations." },
    ],
    gallery: ["Signature Dish", "Private Dining", "Chef's Table", "Weekend Brunch", "Bar Corner", "Dessert Menu"],
    testimonials: [
      { name: "Ananya R.", role: "Regular Guest", quote: "Every dish tastes like it was made for me. This is our go-to spot in {{city}}.", rating: 5 },
      { name: "Karan M.", role: "Food Blogger", quote: "One of the most consistent kitchens I've reviewed this year.", rating: 5 },
      { name: "Sara T.", role: "First-time Visitor", quote: "Booked a table on a whim, ended up staying for three hours.", rating: 5 },
    ],
    faq: [
      { q: "Do you take reservations?", a: "Yes, you can reserve a table directly from this page or by calling us." },
      { q: "Do you offer takeaway or delivery?", a: "Both are available — order ahead for pickup or have it delivered to your door." },
      { q: "Can you accommodate large groups?", a: "Absolutely, we regularly host groups and private events." },
      { q: "Do you have vegetarian options?", a: "Yes, a full vegetarian menu is available alongside our regular offerings." },
      { q: "What are your operating hours?", a: "We're open daily; check the contact section below for exact timings." },
    ],
    cta: { headline: "Hungry Already? Reserve Your Table", button: "Reserve a Table" },
  },

  cafe: {
    key: "cafe",
    label: "Cafe",
    emoji: "☕",
    colors: { primary: "#6F4E37", accent: "#D9A566", dark: "#2A1D14" },
    fonts: { display: "Fraunces", body: "Inter" },
    images: {
      heroQuery: "cozy cafe coffee shop interior morning light",
      gallery: [
        "latte art coffee cup closeup",
        "cozy cafe reading corner armchair",
        "fresh pastries bakery display case",
        "outdoor cafe patio seating",
        "coffee roasting machine barista",
        "busy cafe weekend crowd counter",
      ],
    },
    hero: {
      headline: "Your Favorite Corner for Coffee & Conversation",
      subheadline: "{{businessName}} pours slow, roasts fresh, and keeps {{city}} caffeinated one cup at a time.",
      ctaPrimary: "Order Now",
      ctaSecondary: "See Menu",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} started with a simple idea — great coffee shouldn't be rushed. Today we're a favorite stop in {{city}} for coffee lovers and remote workers alike.",
    },
    services: [
      { title: "Specialty Coffee", description: "Single-origin beans, roasted and brewed fresh.", icon: "Coffee" },
      { title: "Fresh Bakes", description: "Pastries and light bites made every morning.", icon: "Croissant" },
      { title: "Cozy Seating", description: "A calm space to work, meet, or unwind.", icon: "Sofa" },
      { title: "Takeaway & Delivery", description: "Your order, ready fast or delivered hot.", icon: "ShoppingBag" },
    ],
    features: [
      { title: "Ethically Sourced Beans", description: "Direct-trade coffee from trusted growers." },
      { title: "Free Wi-Fi", description: "Fast, reliable internet for work or study." },
      { title: "Pet Friendly", description: "Bring your furry friend along." },
      { title: "Loyalty Rewards", description: "Earn a free cup with every visit." },
    ],
    gallery: ["Latte Art", "Reading Corner", "Fresh Pastries", "Outdoor Seating", "Roasting Station", "Weekend Crowd"],
    testimonials: [
      { name: "Meera J.", role: "Regular", quote: "Best flat white in {{city}}, hands down.", rating: 5 },
      { name: "Yusuf K.", role: "Remote Worker", quote: "My unofficial office. Great wifi, better coffee.", rating: 5 },
      { name: "Priyanka D.", role: "Local Resident", quote: "The pastries sell out for a reason.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer decaf?", a: "Yes, we have decaf options for every drink on the menu." },
      { q: "Can I book the space for an event?", a: "Yes, reach out and we'll set something up for small gatherings." },
      { q: "Do you deliver?", a: "Yes, delivery is available across {{city}}." },
      { q: "Do you sell coffee beans?", a: "Yes, retail bags of our roasted beans are available at the counter." },
      { q: "What are your hours?", a: "Check the contact section below for our current timings." },
    ],
    cta: { headline: "Craving Something Warm?", button: "Order Now" },
  },

  hotel: {
    key: "hotel",
    label: "Hotel",
    emoji: "🏨",
    colors: { primary: "#0F3D3E", accent: "#C9A15A", dark: "#0A1F1F" },
    fonts: { display: "Cormorant Garamond", body: "Inter" },
    images: {
      heroQuery: "luxury hotel lobby interior elegant",
      gallery: [
        "luxury hotel deluxe room bed",
        "hotel rooftop pool view",
        "hotel banquet hall event setup",
        "hotel lobby reception elegant",
        "hotel spa suite relaxation",
        "hotel city view suite window",
      ],
    },
    hero: {
      headline: "A Luxury Stay in the Heart of {{city}}",
      subheadline: "{{businessName}} offers refined comfort, attentive service, and unforgettable stays for every guest.",
      ctaPrimary: "Book Rooms",
      ctaSecondary: "Explore Amenities",
    },
    about: {
      title: "Welcome",
      body: "{{businessName}} blends modern comfort with warm hospitality. Whether you're here for business or leisure, every detail is designed around you.",
    },
    services: [
      { title: "Luxury Rooms", description: "Elegant rooms with premium linens and city views.", icon: "BedDouble" },
      { title: "Fine Dining", description: "In-house restaurant serving local and global cuisine.", icon: "UtensilsCrossed" },
      { title: "Spa & Wellness", description: "Unwind with our curated spa treatments.", icon: "Sparkles" },
      { title: "Event Spaces", description: "Banquet halls for weddings and conferences.", icon: "PartyPopper" },
    ],
    features: [
      { title: "24/7 Concierge", description: "Assistance whenever you need it." },
      { title: "Free Airport Transfer", description: "Complimentary pickup for select bookings." },
      { title: "Rooftop Pool", description: "Relax with a view over {{city}}." },
      { title: "Business Center", description: "Fully equipped for work on the go." },
    ],
    gallery: ["Deluxe Room", "Rooftop Pool", "Banquet Hall", "Lobby", "Spa Suite", "City View Suite"],
    testimonials: [
      { name: "Rohit S.", role: "Business Traveler", quote: "Impeccable service every single time I visit {{city}}.", rating: 5 },
      { name: "Fatima A.", role: "Honeymoon Guest", quote: "Felt like a five-star experience from check-in to check-out.", rating: 5 },
      { name: "David L.", role: "Conference Attendee", quote: "The event team handled everything flawlessly.", rating: 5 },
    ],
    faq: [
      { q: "What is the check-in/check-out time?", a: "Standard check-in is 2 PM and check-out is 11 AM, with flexibility on request." },
      { q: "Do you offer airport transfers?", a: "Yes, complimentary transfers are available for select room categories." },
      { q: "Is breakfast included?", a: "Yes, breakfast is included with most room bookings." },
      { q: "Can you host weddings or events?", a: "Yes, our banquet spaces are designed for events of all sizes." },
      { q: "Is parking available?", a: "Yes, secure on-site parking is available for all guests." },
    ],
    cta: { headline: "Your Stay in {{city}} Starts Here", button: "Book Rooms" },
  },

  gym: {
    key: "gym",
    label: "Gym",
    emoji: "💪",
    colors: { primary: "#111827", accent: "#F97316", dark: "#000000" },
    fonts: { display: "Archivo Black", body: "Inter" },
    images: {
      heroQuery: "modern gym fitness training equipment dramatic",
      gallery: [
        "free weights rack gym floor",
        "group fitness class training",
        "cardio machines gym zone",
        "personal trainer coaching client",
        "gym locker room modern",
        "fitness transformation wall gym",
      ],
    },
    hero: {
      headline: "Train Harder. Become Stronger.",
      subheadline: "{{businessName}} is {{city}}'s home for serious training — expert coaching, real results, no shortcuts.",
      ctaPrimary: "Start Training",
      ctaSecondary: "View Plans",
    },
    about: {
      title: "About the Gym",
      body: "{{businessName}} was built for people who are serious about their fitness journey. State-of-the-art equipment, expert trainers, and a community that pushes you further.",
    },
    services: [
      { title: "Strength Training", description: "Free weights and machines for every level.", icon: "Dumbbell" },
      { title: "Personal Coaching", description: "One-on-one plans built around your goals.", icon: "Users" },
      { title: "Group Classes", description: "HIIT, yoga, and functional training sessions.", icon: "Flame" },
      { title: "Nutrition Guidance", description: "Diet plans to match your training.", icon: "Apple" },
    ],
    features: [
      { title: "Membership Plans", description: "Flexible monthly and annual options." },
      { title: "Certified Trainers", description: "Coaches with real training credentials." },
      { title: "Modern Equipment", description: "Latest strength and cardio machines." },
      { title: "Transformation Tracking", description: "See your progress, tracked and measured." },
    ],
    gallery: ["Free Weights Area", "Group Class", "Cardio Zone", "Personal Training", "Locker Rooms", "Transformation Wall"],
    testimonials: [
      { name: "Vikram P.", role: "Member, 2 years", quote: "Lost 14kg in 6 months with the trainers here. Best decision I made.", rating: 5 },
      { name: "Neha S.", role: "Member", quote: "The coaching is next level — they actually track your progress.", rating: 5 },
      { name: "Arjun T.", role: "Member", quote: "Clean equipment, no crowding, real results.", rating: 5 },
    ],
    faq: [
      { q: "What membership plans do you offer?", a: "We offer monthly, quarterly, and annual plans with flexible add-ons." },
      { q: "Do you offer a free trial?", a: "Yes, a free trial session is available for new members." },
      { q: "Are personal trainers included?", a: "Personal training is available as an add-on to any membership." },
      { q: "What are your operating hours?", a: "We're open early morning through late evening — see the contact section." },
      { q: "Do you have a BMI or fitness assessment?", a: "Yes, every new member gets a complimentary fitness assessment." },
    ],
    cta: { headline: "Your Transformation Starts Today", button: "Start Training" },
  },

  hospital: {
    key: "hospital",
    label: "Hospital",
    emoji: "🏥",
    colors: { primary: "#0C6E5D", accent: "#3FA9F5", dark: "#062B24" },
    fonts: { display: "Source Serif 4", body: "Inter" },
    images: {
      heroQuery: "modern hospital building exterior healthcare",
      gallery: [
        "hospital reception desk clean",
        "hospital emergency ward corridor",
        "doctor consultation room hospital",
        "hospital diagnostic lab equipment",
        "hospital patient room comfortable",
        "hospital operation theatre surgical",
      ],
    },
    hero: {
      headline: "Compassionate Care, Advanced Medicine",
      subheadline: "{{businessName}} delivers trusted healthcare to {{city}}, backed by experienced doctors and modern facilities.",
      ctaPrimary: "Book Appointment",
      ctaSecondary: "Our Departments",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} has served {{city}} with a commitment to patient-first care. Our multidisciplinary team combines expertise with genuine compassion.",
    },
    services: [
      { title: "Emergency Care", description: "24/7 emergency response and treatment.", icon: "Siren" },
      { title: "Specialist Consultations", description: "Access to experienced specialists across departments.", icon: "Stethoscope" },
      { title: "Diagnostics", description: "In-house labs and imaging for fast results.", icon: "Activity" },
      { title: "In-Patient Care", description: "Comfortable rooms and round-the-clock nursing.", icon: "BedDouble" },
    ],
    features: [
      { title: "24/7 Emergency", description: "Always open, always ready." },
      { title: "Experienced Doctors", description: "Specialists across every major department." },
      { title: "Modern Equipment", description: "Advanced diagnostic and treatment technology." },
      { title: "Insurance Support", description: "Cashless treatment with major insurance partners." },
    ],
    gallery: ["Reception", "Emergency Ward", "Consultation Room", "Diagnostic Lab", "Patient Room", "Operation Theatre"],
    testimonials: [
      { name: "Suresh K.", role: "Patient", quote: "The doctors took the time to explain everything clearly. Truly grateful.", rating: 5 },
      { name: "Lakshmi N.", role: "Patient's Family", quote: "Emergency response was fast and the staff was compassionate throughout.", rating: 5 },
      { name: "Imran H.", role: "Patient", quote: "Clean facility, professional staff, minimal wait times.", rating: 5 },
    ],
    faq: [
      { q: "Do you have 24/7 emergency services?", a: "Yes, our emergency department operates around the clock." },
      { q: "Which departments are available?", a: "We have multiple specialist departments — see the departments section above." },
      { q: "Do you accept insurance?", a: "Yes, we work with most major insurance providers for cashless treatment." },
      { q: "How do I book an appointment?", a: "You can book directly through this page or by calling our front desk." },
      { q: "Do you offer online consultations?", a: "Yes, teleconsultations are available for select departments." },
    ],
    cta: { headline: "Your Health, Our Priority", button: "Book Appointment" },
  },

  clinic: {
    key: "clinic",
    label: "Clinic",
    emoji: "🩺",
    colors: { primary: "#1D7A6E", accent: "#7DD3C0", dark: "#0B2D28" },
    fonts: { display: "Source Serif 4", body: "Inter" },
    images: {
      heroQuery: "medical clinic modern interior clean",
      gallery: [
        "clinic reception area waiting",
        "doctor consultation room clinic",
        "clinic waiting lounge chairs",
        "clinic treatment room equipment",
        "medical lab corner clinic",
        "clinic front desk staff",
      ],
    },
    hero: {
      headline: "Trusted Care, Close to Home",
      subheadline: "{{businessName}} offers thorough, personal healthcare for {{city}} residents — no long waits, real attention.",
      ctaPrimary: "Book Appointment",
      ctaSecondary: "Our Services",
    },
    about: {
      title: "About the Clinic",
      body: "{{businessName}} is built around one idea — healthcare should be personal. Our doctors take the time to listen, diagnose accurately, and treat with care.",
    },
    services: [
      { title: "General Consultation", description: "Comprehensive check-ups for all ages.", icon: "Stethoscope" },
      { title: "Health Screenings", description: "Preventive tests to catch issues early.", icon: "ClipboardCheck" },
      { title: "Minor Procedures", description: "On-site care for minor treatments.", icon: "Syringe" },
      { title: "Follow-up Care", description: "Ongoing monitoring for chronic conditions.", icon: "Calendar" },
    ],
    features: [
      { title: "Experienced Physicians", description: "Trusted doctors with years of practice." },
      { title: "Same-Day Appointments", description: "Fast access when you need it most." },
      { title: "Modern Facility", description: "Clean, well-equipped consultation rooms." },
      { title: "Digital Records", description: "Your history, accessible whenever needed." },
    ],
    gallery: ["Reception Area", "Consultation Room", "Waiting Lounge", "Treatment Room", "Lab Corner", "Front Desk"],
    testimonials: [
      { name: "Divya M.", role: "Patient", quote: "Never had to wait long, and the doctor genuinely listened.", rating: 5 },
      { name: "Rakesh V.", role: "Patient", quote: "My go-to clinic for the whole family.", rating: 5 },
      { name: "Anjali B.", role: "Patient", quote: "Professional, clean, and easy to book.", rating: 5 },
    ],
    faq: [
      { q: "Do I need an appointment?", a: "Appointments are recommended, but walk-ins are accommodated when possible." },
      { q: "What conditions do you treat?", a: "We handle general consultations, screenings, and a wide range of common conditions." },
      { q: "Do you accept insurance?", a: "Yes, most major insurance plans are accepted." },
      { q: "Are online consultations available?", a: "Yes, for follow-ups and minor concerns." },
      { q: "What are your hours?", a: "See the contact section below for current clinic hours." },
    ],
    cta: { headline: "Book Your Visit Today", button: "Book Appointment" },
  },

  dentist: {
    key: "dentist",
    label: "Dentist",
    emoji: "🦷",
    colors: { primary: "#0E7C9D", accent: "#8FE3D6", dark: "#062230" },
    fonts: { display: "Poppins", body: "Inter" },
    images: {
      heroQuery: "modern dental clinic office bright",
      gallery: [
        "dental treatment room chair",
        "dental clinic reception area",
        "dentist chair equipment closeup",
        "dental sterilization area clean",
        "dental consultation room modern",
        "smile gallery dental before after",
      ],
    },
    hero: {
      headline: "A Healthier Smile Starts Here",
      subheadline: "{{businessName}} provides gentle, modern dental care for {{city}} — from routine cleanings to complete smile makeovers.",
      ctaPrimary: "Book Appointment",
      ctaSecondary: "Our Treatments",
    },
    about: {
      title: "About Our Practice",
      body: "{{businessName}} combines advanced dental technology with a calm, patient-first approach. We believe every visit should leave you smiling — literally.",
    },
    services: [
      { title: "Routine Checkups", description: "Cleanings and exams to keep your smile healthy.", icon: "Smile" },
      { title: "Cosmetic Dentistry", description: "Whitening, veneers, and smile makeovers.", icon: "Sparkles" },
      { title: "Root Canal Treatment", description: "Painless, precise endodontic care.", icon: "Activity" },
      { title: "Braces & Aligners", description: "Straighten teeth with modern orthodontics.", icon: "Aperture" },
    ],
    features: [
      { title: "Pain-Free Procedures", description: "Modern techniques for a comfortable visit." },
      { title: "Experienced Dentists", description: "Years of specialized dental expertise." },
      { title: "Digital X-Rays", description: "Faster, safer diagnostics." },
      { title: "Flexible Scheduling", description: "Evening and weekend slots available." },
    ],
    gallery: ["Treatment Room", "Reception", "Dental Chair", "Sterilization Area", "Consultation Room", "Smile Gallery"],
    testimonials: [
      { name: "Farah S.", role: "Patient", quote: "The most painless dental visit I've ever had.", rating: 5 },
      { name: "Nikhil J.", role: "Patient", quote: "Great with kids — my daughter actually looks forward to visits.", rating: 5 },
      { name: "Ritu A.", role: "Patient", quote: "Transformed my smile in a few sessions. Highly recommend.", rating: 5 },
    ],
    faq: [
      { q: "Do you treat dental emergencies?", a: "Yes, we accommodate emergency cases as quickly as possible." },
      { q: "Do you offer teeth whitening?", a: "Yes, in-office and take-home whitening options are available." },
      { q: "Is the treatment painful?", a: "We use modern, minimally invasive techniques to keep procedures comfortable." },
      { q: "Do you treat children?", a: "Yes, we offer pediatric dental care in a friendly environment." },
      { q: "Do you accept insurance?", a: "Most dental insurance plans are accepted — ask our front desk for details." },
    ],
    cta: { headline: "Ready for a Brighter Smile?", button: "Book Appointment" },
  },

  salon: {
    key: "salon",
    label: "Salon",
    emoji: "💇",
    colors: { primary: "#8E2A5B", accent: "#F2B8D4", dark: "#2E0F1E" },
    fonts: { display: "Cormorant Garamond", body: "Inter" },
    images: {
      heroQuery: "modern hair salon interior styling chairs",
      gallery: [
        "hair styling chair salon mirror",
        "hair color bar salon products",
        "facial treatment room salon spa",
        "bridal hair makeup look",
        "nail studio manicure salon",
        "salon waiting lounge modern",
      ],
    },
    hero: {
      headline: "Look Good. Feel Unstoppable.",
      subheadline: "{{businessName}} is {{city}}'s destination for hair, beauty, and self-care — where every visit feels like an upgrade.",
      ctaPrimary: "Book Now",
      ctaSecondary: "See Services",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} brings expert stylists and premium products together for an experience that goes beyond a haircut. This is where you come to feel your best.",
    },
    services: [
      { title: "Hair Styling", description: "Cuts, colors, and styling by expert stylists.", icon: "Scissors" },
      { title: "Beauty Treatments", description: "Facials, makeup, and skincare rituals.", icon: "Sparkles" },
      { title: "Spa Services", description: "Relaxing treatments to unwind and recharge.", icon: "Flower" },
      { title: "Bridal Packages", description: "Complete looks for your big day.", icon: "Gem" },
    ],
    features: [
      { title: "Expert Stylists", description: "Trained professionals with a keen eye for detail." },
      { title: "Premium Products", description: "Only trusted, high-quality brands used." },
      { title: "Easy Online Booking", description: "Book your slot in seconds." },
      { title: "Seasonal Offers", description: "Regular packages and member discounts." },
    ],
    gallery: ["Styling Chair", "Color Bar", "Facial Room", "Bridal Look", "Nail Studio", "Waiting Lounge"],
    testimonials: [
      { name: "Simran K.", role: "Client", quote: "Left feeling like a completely new person. Booking again next month.", rating: 5 },
      { name: "Tanya R.", role: "Bridal Client", quote: "My bridal look was flawless, exactly what I dreamed of.", rating: 5 },
      { name: "Aisha M.", role: "Client", quote: "The best colorist I've found in {{city}}.", rating: 5 },
    ],
    faq: [
      { q: "Do I need to book in advance?", a: "We recommend booking ahead, especially on weekends." },
      { q: "Do you offer bridal packages?", a: "Yes, complete bridal and party packages are available." },
      { q: "What brands do you use?", a: "We use premium, salon-grade products for every service." },
      { q: "Do you have offers for first-time clients?", a: "Yes, ask about our welcome offer when you book." },
      { q: "Can I request a specific stylist?", a: "Absolutely, just mention your preference while booking." },
    ],
    cta: { headline: "Your Glow-Up Awaits", button: "Book Now" },
  },

  spa: {
    key: "spa",
    label: "Spa",
    emoji: "🌸",
    colors: { primary: "#5B7B6B", accent: "#E7C8A8", dark: "#1F2B24" },
    fonts: { display: "Cormorant Garamond", body: "Inter" },
    images: {
      heroQuery: "luxury spa wellness interior calm",
      gallery: [
        "spa treatment room candles",
        "spa relaxation lounge robe",
        "massage therapy suite spa",
        "spa steam room wellness",
        "spa reception calm interior",
        "spa couples suite treatment",
      ],
    },
    hero: {
      headline: "Slow Down. Restore. Renew.",
      subheadline: "{{businessName}} offers a sanctuary of calm in {{city}} — therapeutic treatments designed to restore balance.",
      ctaPrimary: "Book a Session",
      ctaSecondary: "Explore Treatments",
    },
    about: {
      title: "Our Philosophy",
      body: "{{businessName}} was created as a retreat from the everyday — a space to breathe, unwind, and reconnect with yourself through mindful, therapeutic care.",
    },
    services: [
      { title: "Massage Therapy", description: "Deep tissue, Swedish, and aromatherapy massages.", icon: "HandHeart" },
      { title: "Facial Treatments", description: "Rejuvenating facials for every skin type.", icon: "Sparkles" },
      { title: "Body Rituals", description: "Scrubs and wraps for total renewal.", icon: "Flower2" },
      { title: "Couples Packages", description: "Shared relaxation experiences.", icon: "Users" },
    ],
    features: [
      { title: "Certified Therapists", description: "Trained in traditional and modern techniques." },
      { title: "Serene Ambience", description: "A calm space designed for real relaxation." },
      { title: "Organic Products", description: "Natural, skin-friendly treatment products." },
      { title: "Membership Plans", description: "Regular self-care, made affordable." },
    ],
    gallery: ["Treatment Room", "Relaxation Lounge", "Massage Suite", "Steam Room", "Reception", "Couples Suite"],
    testimonials: [
      { name: "Reema P.", role: "Member", quote: "The most relaxing two hours of my month, every time.", rating: 5 },
      { name: "Vivek N.", role: "Client", quote: "Booked for stress relief, left feeling like a new person.", rating: 5 },
      { name: "Zoya I.", role: "Client", quote: "Beautifully designed space, incredibly skilled therapists.", rating: 5 },
    ],
    faq: [
      { q: "What should I expect on my first visit?", a: "A brief consultation followed by your chosen treatment in a calm, private room." },
      { q: "Do you offer couples sessions?", a: "Yes, our couples suite is available for shared treatments." },
      { q: "What products do you use?", a: "We use organic, skin-friendly products throughout our treatments." },
      { q: "Do you have membership plans?", a: "Yes, monthly memberships offer discounted regular sessions." },
      { q: "How far in advance should I book?", a: "We recommend booking 2-3 days ahead, especially for weekends." },
    ],
    cta: { headline: "You Deserve This Moment", button: "Book a Session" },
  },

  school: {
    key: "school",
    label: "School",
    emoji: "🎓",
    colors: { primary: "#1E3A8A", accent: "#FBBF24", dark: "#0B1739" },
    fonts: { display: "Poppins", body: "Inter" },
    images: {
      heroQuery: "modern school campus building students",
      gallery: [
        "school classroom students learning",
        "school sports ground playing",
        "school science lab students",
        "school library reading students",
        "school assembly hall students",
        "school art studio creative",
      ],
    },
    hero: {
      headline: "Where Every Student Finds Their Path",
      subheadline: "{{businessName}} nurtures curiosity, character, and confidence in every student across {{city}}.",
      ctaPrimary: "Schedule a Visit",
      ctaSecondary: "Explore Programs",
    },
    about: {
      title: "Our Mission",
      body: "{{businessName}} is committed to holistic education — combining academic excellence with strong values, creativity, and real-world skills.",
    },
    services: [
      { title: "Academic Programs", description: "Structured curriculum across all grade levels.", icon: "BookOpen" },
      { title: "Extracurriculars", description: "Sports, arts, and clubs for well-rounded growth.", icon: "Trophy" },
      { title: "Experienced Faculty", description: "Dedicated teachers focused on every student.", icon: "GraduationCap" },
      { title: "Modern Campus", description: "Safe, well-equipped learning facilities.", icon: "Building2" },
    ],
    features: [
      { title: "Small Class Sizes", description: "More attention for every student." },
      { title: "Experienced Educators", description: "Teachers passionate about student growth." },
      { title: "Safe Campus", description: "Secure, supervised environment throughout the day." },
      { title: "Parent Communication", description: "Regular updates on student progress." },
    ],
    gallery: ["Classroom", "Sports Ground", "Science Lab", "Library", "Assembly Hall", "Art Studio"],
    testimonials: [
      { name: "Mrs. Kapoor", role: "Parent", quote: "My daughter has grown so much in confidence since joining.", rating: 5 },
      { name: "Mr. Reddy", role: "Parent", quote: "The teachers genuinely care about each child's progress.", rating: 5 },
      { name: "Ms. Fernandes", role: "Parent", quote: "Best decision we made for our son's education.", rating: 5 },
    ],
    faq: [
      { q: "What grade levels do you offer?", a: "We offer programs across multiple grade levels — contact us for specifics." },
      { q: "How do I schedule a campus visit?", a: "You can request a visit directly through this page." },
      { q: "What is the admission process?", a: "Admissions involve a simple application and orientation process." },
      { q: "Do you offer transport?", a: "Yes, transport facilities are available across {{city}}." },
      { q: "What extracurriculars are available?", a: "Sports, arts, music, and academic clubs are all part of our program." },
    ],
    cta: { headline: "Give Your Child the Best Start", button: "Schedule a Visit" },
  },

  coaching: {
    key: "coaching",
    label: "Coaching Institute",
    emoji: "📚",
    colors: { primary: "#1D4ED8", accent: "#22C55E", dark: "#0B1E4D" },
    fonts: { display: "Poppins", body: "Inter" },
    images: {
      heroQuery: "students studying classroom coaching institute",
      gallery: [
        "students classroom coaching session",
        "doubt clearing class students teacher",
        "mock test hall students exam",
        "faculty discussion whiteboard",
        "students study area library",
        "result day celebration students",
      ],
    },
    hero: {
      headline: "Results That Speak For Themselves",
      subheadline: "{{businessName}} helps students across {{city}} achieve top scores through focused, expert-led coaching.",
      ctaPrimary: "Enroll Now",
      ctaSecondary: "View Courses",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} was founded to give students a real edge — expert faculty, structured programs, and a track record of results.",
    },
    services: [
      { title: "Exam Preparation", description: "Focused prep for competitive and board exams.", icon: "PenTool" },
      { title: "Doubt-Solving Sessions", description: "One-on-one help whenever students are stuck.", icon: "MessageCircle" },
      { title: "Mock Tests", description: "Regular tests to track progress and readiness.", icon: "ClipboardCheck" },
      { title: "Small Batch Sizes", description: "Personalized attention for every student.", icon: "Users" },
    ],
    features: [
      { title: "Experienced Faculty", description: "Educators with proven track records." },
      { title: "Result-Oriented Approach", description: "Structured plans built around outcomes." },
      { title: "Flexible Batches", description: "Weekday and weekend options available." },
      { title: "Study Material Included", description: "Comprehensive notes and practice sets." },
    ],
    gallery: ["Classroom Session", "Doubt-Clearing Class", "Mock Test Hall", "Faculty Discussion", "Study Area", "Result Day"],
    testimonials: [
      { name: "Aditya S.", role: "Student", quote: "Cracked my entrance exam thanks to the structured approach here.", rating: 5 },
      { name: "Pooja R.", role: "Parent", quote: "The faculty tracks every student's progress closely.", rating: 5 },
      { name: "Rahul B.", role: "Student", quote: "Best doubt-solving support I've had anywhere.", rating: 5 },
    ],
    faq: [
      { q: "What courses do you offer?", a: "We offer preparation programs for various competitive and academic exams." },
      { q: "What is the batch size?", a: "We maintain small batches for focused, personal attention." },
      { q: "Do you provide study material?", a: "Yes, comprehensive material is included with every course." },
      { q: "Are demo classes available?", a: "Yes, you can attend a free demo class before enrolling." },
      { q: "Do you offer online classes?", a: "Yes, both online and offline batches are available." },
    ],
    cta: { headline: "Your Success Starts Here", button: "Enroll Now" },
  },

  realestate: {
    key: "realestate",
    label: "Real Estate",
    emoji: "🏠",
    colors: { primary: "#14532D", accent: "#D4B483", dark: "#0A1F14" },
    fonts: { display: "Fraunces", body: "Inter" },
    images: {
      heroQuery: "modern house exterior real estate property",
      gallery: [
        "featured property listing exterior",
        "modern apartment interior real estate",
        "office space commercial property",
        "real estate agent site visit",
        "real estate consultation meeting",
        "house key handover real estate",
      ],
    },
    hero: {
      headline: "Find a Home You'll Love in {{city}}",
      subheadline: "{{businessName}} helps you buy, sell, and invest in property with confidence and expert guidance.",
      ctaPrimary: "View Listings",
      ctaSecondary: "Talk to an Agent",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} has helped countless families and investors find the right property in {{city}}. We combine local expertise with honest, transparent advice.",
    },
    services: [
      { title: "Residential Sales", description: "Homes and apartments for every budget.", icon: "Home" },
      { title: "Commercial Property", description: "Office and retail spaces built for growth.", icon: "Building2" },
      { title: "Property Investment", description: "Guidance for smart, long-term investments.", icon: "TrendingUp" },
      { title: "Rental Assistance", description: "Fast, verified rental listings.", icon: "KeyRound" },
    ],
    features: [
      { title: "Verified Listings", description: "Every property is checked and confirmed." },
      { title: "Local Market Expertise", description: "Deep knowledge of {{city}}'s neighborhoods." },
      { title: "End-to-End Support", description: "From search to paperwork, fully assisted." },
      { title: "Transparent Pricing", description: "No hidden fees, ever." },
    ],
    gallery: ["Featured Listing", "Modern Apartment", "Office Space", "Site Visit", "Consultation", "Key Handover"],
    testimonials: [
      { name: "Manish G.", role: "Home Buyer", quote: "Found our dream home in under a month, smooth process throughout.", rating: 5 },
      { name: "Sunita R.", role: "Investor", quote: "Honest advice that actually put my interests first.", rating: 5 },
      { name: "Aakash V.", role: "Tenant", quote: "Verified listings meant no surprises on move-in day.", rating: 5 },
    ],
    faq: [
      { q: "Do you help with both buying and renting?", a: "Yes, we assist with residential sales, rentals, and commercial property." },
      { q: "Are your listings verified?", a: "Yes, every listing is personally verified before it goes live." },
      { q: "Do you charge brokerage fees?", a: "Fees are transparent and discussed upfront before any commitment." },
      { q: "Can you help with home loans?", a: "Yes, we can connect you with trusted loan advisors." },
      { q: "Do you handle commercial property?", a: "Yes, office and retail spaces are part of our portfolio." },
    ],
    cta: { headline: "Ready to Find Your Next Property?", button: "View Listings" },
  },

  lawfirm: {
    key: "lawfirm",
    label: "Law Firm",
    emoji: "⚖️",
    colors: { primary: "#1F2937", accent: "#B08D57", dark: "#0A0D12" },
    fonts: { display: "Source Serif 4", body: "Inter" },
    images: {
      heroQuery: "law office interior professional wood paneling",
      gallery: [
        "law firm conference room meeting",
        "lawyer consultation room desk",
        "law office reception elegant",
        "law library books shelves",
        "contract signing room office",
        "law firm team meeting discussion",
      ],
    },
    hero: {
      headline: "Trusted Legal Counsel for {{city}}",
      subheadline: "{{businessName}} provides clear, strategic legal guidance for individuals and businesses alike.",
      ctaPrimary: "Book a Consultation",
      ctaSecondary: "Practice Areas",
    },
    about: {
      title: "About the Firm",
      body: "{{businessName}} has represented clients across {{city}} with integrity and precision. We believe good legal advice should be clear, honest, and always in your corner.",
    },
    services: [
      { title: "Corporate Law", description: "Contracts, compliance, and business advisory.", icon: "Briefcase" },
      { title: "Civil Litigation", description: "Skilled representation in civil disputes.", icon: "Gavel" },
      { title: "Family Law", description: "Compassionate guidance through sensitive matters.", icon: "Users" },
      { title: "Property Law", description: "Legal support for real estate transactions.", icon: "Home" },
    ],
    features: [
      { title: "Experienced Advocates", description: "Decades of combined courtroom experience." },
      { title: "Confidential Consultations", description: "Your matters handled with complete discretion." },
      { title: "Transparent Fees", description: "Clear pricing, no hidden charges." },
      { title: "Responsive Communication", description: "Direct access to your legal team." },
    ],
    gallery: ["Conference Room", "Consultation Room", "Reception", "Library", "Signing Room", "Team Meeting"],
    testimonials: [
      { name: "Anil K.", role: "Client", quote: "Clear, honest advice throughout a stressful process.", rating: 5 },
      { name: "Meenal S.", role: "Business Owner", quote: "Handled our contracts with real precision and care.", rating: 5 },
      { name: "Joseph P.", role: "Client", quote: "Responsive, professional, and genuinely on my side.", rating: 5 },
    ],
    faq: [
      { q: "How do I schedule a consultation?", a: "You can book a consultation directly through this page or by calling us." },
      { q: "What areas of law do you practice?", a: "We handle corporate, civil, family, and property law matters." },
      { q: "Is the first consultation free?", a: "An initial consultation fee applies; details are shared when you book." },
      { q: "How are fees structured?", a: "Fees vary by case type and are discussed transparently upfront." },
      { q: "Do you handle cases outside {{city}}?", a: "Yes, we represent clients across the wider region as needed." },
    ],
    cta: { headline: "Discuss Your Case With Us", button: "Book a Consultation" },
  },

  cardealer: {
    key: "cardealer",
    label: "Car Dealer",
    emoji: "🚗",
    colors: { primary: "#111827", accent: "#EF4444", dark: "#000000" },
    fonts: { display: "Archivo Black", body: "Inter" },
    images: {
      heroQuery: "car showroom dealership vehicles display",
      gallery: [
        "car showroom floor vehicles",
        "test drive car customer",
        "car service bay mechanic",
        "new car arrivals showroom",
        "car dealership finance desk",
        "car delivery day handover",
      ],
    },
    hero: {
      headline: "Drive Home Something You'll Love",
      subheadline: "{{businessName}} offers a curated selection of vehicles, honest pricing, and hassle-free service in {{city}}.",
      ctaPrimary: "Browse Inventory",
      ctaSecondary: "Book a Test Drive",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} has been helping {{city}} find the right vehicle for years — new, used, and everything in between, backed by real after-sales support.",
    },
    services: [
      { title: "New Vehicle Sales", description: "Latest models with complete warranty support.", icon: "Car" },
      { title: "Certified Pre-Owned", description: "Thoroughly inspected used vehicles.", icon: "ShieldCheck" },
      { title: "Financing Options", description: "Flexible loan and EMI plans.", icon: "Wallet" },
      { title: "After-Sales Service", description: "Maintenance and repairs by certified technicians.", icon: "Wrench" },
    ],
    features: [
      { title: "Wide Inventory", description: "A vehicle for every need and budget." },
      { title: "Transparent Pricing", description: "No hidden costs, ever." },
      { title: "Easy Financing", description: "Loan approvals processed quickly." },
      { title: "Trade-In Support", description: "Fair value for your current vehicle." },
    ],
    gallery: ["Showroom Floor", "Test Drive", "Service Bay", "New Arrivals", "Finance Desk", "Delivery Day"],
    testimonials: [
      { name: "Deepak R.", role: "Customer", quote: "Smooth buying experience from test drive to delivery.", rating: 5 },
      { name: "Farhan A.", role: "Customer", quote: "Got a fair trade-in value and a great deal on my new car.", rating: 5 },
      { name: "Shalini T.", role: "Customer", quote: "Their service team keeps my car running perfectly.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer financing?", a: "Yes, we work with multiple lenders to offer flexible EMI plans." },
      { q: "Can I trade in my old vehicle?", a: "Yes, we offer fair market value for trade-ins." },
      { q: "Do certified pre-owned cars come with warranty?", a: "Yes, all certified pre-owned vehicles include a warranty period." },
      { q: "Can I book a test drive online?", a: "Yes, test drives can be scheduled directly through this page." },
      { q: "Do you provide after-sales service?", a: "Yes, our service center handles maintenance and repairs." },
    ],
    cta: { headline: "Ready for a Test Drive?", button: "Book a Test Drive" },
  },

  bikeshowroom: {
    key: "bikeshowroom",
    label: "Bike Showroom",
    emoji: "🏍️",
    colors: { primary: "#0F172A", accent: "#F59E0B", dark: "#000000" },
    fonts: { display: "Archivo Black", body: "Inter" },
    images: {
      heroQuery: "motorcycle showroom bikes display modern",
      gallery: [
        "motorcycle showroom floor bikes",
        "motorcycle test ride rider",
        "bike service center mechanic",
        "new motorcycle launch display",
        "spare parts counter motorcycle",
        "motorcycle delivery day customer",
      ],
    },
    hero: {
      headline: "Ride Beyond the Ordinary",
      subheadline: "{{businessName}} brings {{city}} the latest bikes, genuine parts, and expert servicing under one roof.",
      ctaPrimary: "Browse Bikes",
      ctaSecondary: "Book a Test Ride",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} is {{city}}'s trusted destination for two-wheelers — from daily commuters to performance machines, with service you can rely on.",
    },
    services: [
      { title: "New Bike Sales", description: "The latest models across every category.", icon: "Bike" },
      { title: "Genuine Spare Parts", description: "100% original parts and accessories.", icon: "Cog" },
      { title: "Service & Repairs", description: "Skilled technicians for every make and model.", icon: "Wrench" },
      { title: "Finance Options", description: "Easy EMI plans for every budget.", icon: "Wallet" },
    ],
    features: [
      { title: "Wide Model Range", description: "Something for every rider and budget." },
      { title: "Genuine Parts Only", description: "No compromises on quality." },
      { title: "Expert Technicians", description: "Trained specifically on modern bike systems." },
      { title: "Easy EMI", description: "Own your bike with flexible monthly plans." },
    ],
    gallery: ["Showroom Floor", "Test Ride", "Service Center", "New Launch", "Spare Parts Counter", "Delivery Day"],
    testimonials: [
      { name: "Rohan D.", role: "Customer", quote: "Great range and the staff actually know their bikes.", rating: 5 },
      { name: "Sameer L.", role: "Customer", quote: "Service turnaround was quick and totally transparent.", rating: 5 },
      { name: "Kavya P.", role: "Customer", quote: "Got my dream bike with an easy financing plan.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer test rides?", a: "Yes, test rides can be booked directly through this page." },
      { q: "Do you sell genuine spare parts?", a: "Yes, only 100% genuine parts and accessories are stocked." },
      { q: "What financing options are available?", a: "Flexible EMI plans are available through our finance partners." },
      { q: "Do you service all bike brands?", a: "Our technicians are trained to service most major brands." },
      { q: "Is there a warranty on new bikes?", a: "Yes, manufacturer warranty applies to all new bike purchases." },
    ],
    cta: { headline: "Find Your Perfect Ride", button: "Browse Bikes" },
  },

  furniture: {
    key: "furniture",
    label: "Furniture",
    emoji: "🛋️",
    colors: { primary: "#6B4226", accent: "#D9C2A6", dark: "#241408" },
    fonts: { display: "Fraunces", body: "Inter" },
    images: {
      heroQuery: "furniture showroom interior sofa display",
      gallery: [
        "living room furniture set sofa",
        "bedroom furniture collection bed",
        "furniture showroom floor display",
        "custom furniture order workshop",
        "furniture workshop craftsman wood",
        "furniture delivery team truck",
      ],
    },
    hero: {
      headline: "Furniture That Feels Like Home",
      subheadline: "{{businessName}} brings handcrafted, quality furniture to {{city}} — built to last, styled to love.",
      ctaPrimary: "Shop Collection",
      ctaSecondary: "Visit Showroom",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} designs and crafts furniture meant to be lived with, not just looked at. Every piece is chosen for comfort, durability, and timeless style.",
    },
    services: [
      { title: "Living Room", description: "Sofas, recliners, and coffee tables.", icon: "Sofa" },
      { title: "Bedroom", description: "Beds, wardrobes, and storage solutions.", icon: "BedDouble" },
      { title: "Custom Furniture", description: "Made-to-order pieces for your space.", icon: "Ruler" },
      { title: "Home Delivery", description: "Safe delivery and professional assembly.", icon: "Truck" },
    ],
    features: [
      { title: "Handcrafted Quality", description: "Built by skilled craftsmen, piece by piece." },
      { title: "Premium Materials", description: "Solid wood and durable upholstery." },
      { title: "Custom Sizing", description: "Furniture made to fit your exact space." },
      { title: "Easy Financing", description: "No-cost EMI options available." },
    ],
    gallery: ["Living Room Set", "Bedroom Collection", "Showroom Floor", "Custom Order", "Workshop", "Delivery Team"],
    testimonials: [
      { name: "Nidhi S.", role: "Customer", quote: "The sofa quality is outstanding — worth every rupee.", rating: 5 },
      { name: "Harish M.", role: "Customer", quote: "They built a custom wardrobe that fit our space perfectly.", rating: 5 },
      { name: "Ovais K.", role: "Customer", quote: "Delivery and assembly were smooth and professional.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer custom furniture?", a: "Yes, we build made-to-order pieces to fit your exact requirements." },
      { q: "What is your delivery timeline?", a: "Standard pieces ship within days; custom orders take longer, as discussed at purchase." },
      { q: "Do you offer EMI options?", a: "Yes, no-cost EMI is available on select purchases." },
      { q: "What materials do you use?", a: "We use solid wood and premium upholstery fabrics across our range." },
      { q: "Is assembly included?", a: "Yes, professional assembly is included with delivery." },
    ],
    cta: { headline: "Furnish Your Space Beautifully", button: "Shop Collection" },
  },

  electronics: {
    key: "electronics",
    label: "Electronics",
    emoji: "📱",
    colors: { primary: "#1E293B", accent: "#38BDF8", dark: "#0B1120" },
    fonts: { display: "Space Grotesk", body: "Inter" },
    images: {
      heroQuery: "electronics store gadgets technology bright",
      gallery: [
        "electronics store front modern",
        "mobile phones section store",
        "home appliance floor store",
        "electronics repair counter technician",
        "new gadget launch display",
        "customer pickup electronics store",
      ],
    },
    hero: {
      headline: "The Latest Tech, Right in {{city}}",
      subheadline: "{{businessName}} stocks the newest electronics with genuine warranty and expert after-sales support.",
      ctaPrimary: "Shop Now",
      ctaSecondary: "View Offers",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} has been {{city}}'s trusted electronics store — genuine products, competitive prices, and support that doesn't end at checkout.",
    },
    services: [
      { title: "Mobiles & Laptops", description: "The latest devices from top brands.", icon: "Smartphone" },
      { title: "Home Appliances", description: "Quality appliances for every home.", icon: "Plug" },
      { title: "Repair Services", description: "Certified technicians for quick fixes.", icon: "Wrench" },
      { title: "Extended Warranty", description: "Extra protection for peace of mind.", icon: "ShieldCheck" },
    ],
    features: [
      { title: "100% Genuine Products", description: "Authorized dealer for all major brands." },
      { title: "Best Price Guarantee", description: "Competitive pricing, always." },
      { title: "Easy EMI", description: "No-cost EMI on eligible purchases." },
      { title: "Fast Repairs", description: "Most repairs completed within 24 hours." },
    ],
    gallery: ["Store Front", "Mobile Section", "Appliance Floor", "Repair Counter", "New Launch Display", "Customer Pickup"],
    testimonials: [
      { name: "Tarun B.", role: "Customer", quote: "Genuine products and the best price I found in {{city}}.", rating: 5 },
      { name: "Swati K.", role: "Customer", quote: "Got my phone screen fixed within a few hours.", rating: 5 },
      { name: "Irfan D.", role: "Customer", quote: "Great after-sales support, unlike other stores.", rating: 5 },
    ],
    faq: [
      { q: "Do you sell genuine products?", a: "Yes, we're an authorized dealer for all brands we stock." },
      { q: "Do you offer repair services?", a: "Yes, our certified technicians handle most repairs same-day." },
      { q: "Is EMI available?", a: "Yes, no-cost EMI is available on eligible purchases." },
      { q: "Do you offer extended warranty?", a: "Yes, extended warranty plans can be added at purchase." },
      { q: "Can I exchange my old device?", a: "Yes, exchange offers are available on select products." },
    ],
    cta: { headline: "Upgrade Your Tech Today", button: "Shop Now" },
  },

  jewellery: {
    key: "jewellery",
    label: "Jewellery",
    emoji: "💎",
    colors: { primary: "#7A1F3D", accent: "#D4AF37", dark: "#240A14" },
    fonts: { display: "Cormorant Garamond", body: "Inter" },
    images: {
      heroQuery: "jewellery showroom diamond gold display",
      gallery: [
        "bridal jewellery set gold",
        "diamond jewellery collection showcase",
        "gold jewellery display case",
        "custom jewellery design sketch",
        "jewellery showroom interior elegant",
        "jewellery certification counter",
      ],
    },
    hero: {
      headline: "Timeless Jewellery, Made to Be Treasured",
      subheadline: "{{businessName}} crafts fine jewellery for {{city}}'s most memorable moments — certified, elegant, unforgettable.",
      ctaPrimary: "Explore Collection",
      ctaSecondary: "Book a Visit",
    },
    about: {
      title: "Our Craft",
      body: "{{businessName}} has been trusted for generations to craft jewellery that lasts a lifetime. Every piece is certified, carefully made, and designed to be cherished.",
    },
    services: [
      { title: "Bridal Collection", description: "Exquisite sets for weddings and ceremonies.", icon: "Gem" },
      { title: "Custom Design", description: "Bespoke pieces made to your vision.", icon: "PenTool" },
      { title: "Gold & Diamond", description: "Certified gold and diamond jewellery.", icon: "Sparkles" },
      { title: "Old Gold Exchange", description: "Fair valuation on exchange purchases.", icon: "Repeat" },
    ],
    features: [
      { title: "Certified Purity", description: "Hallmarked gold, certified diamonds." },
      { title: "Custom Designs", description: "Bring your vision to life with our designers." },
      { title: "Lifetime Buyback", description: "Trusted buyback and exchange policy." },
      { title: "Secure Shopping", description: "Insured shipping and secure in-store experience." },
    ],
    gallery: ["Bridal Set", "Diamond Collection", "Gold Jewellery", "Custom Design", "Showroom", "Certification Counter"],
    testimonials: [
      { name: "Radhika S.", role: "Customer", quote: "My bridal set exceeded every expectation.", rating: 5 },
      { name: "Naveen T.", role: "Customer", quote: "Trusted purity and transparent pricing every time.", rating: 5 },
      { name: "Bhavna J.", role: "Customer", quote: "The custom design team brought my idea to life beautifully.", rating: 5 },
    ],
    faq: [
      { q: "Is your gold hallmarked?", a: "Yes, all our gold jewellery is BIS hallmarked." },
      { q: "Do you offer custom design services?", a: "Yes, our design team creates bespoke pieces to your specifications." },
      { q: "Do you have an exchange policy?", a: "Yes, we offer fair valuation on old gold exchange." },
      { q: "Are your diamonds certified?", a: "Yes, all diamonds come with proper certification." },
      { q: "Do you offer bridal collections?", a: "Yes, complete bridal sets are available across various price ranges." },
    ],
    cta: { headline: "Find a Piece to Treasure", button: "Explore Collection" },
  },

  fashion: {
    key: "fashion",
    label: "Fashion",
    emoji: "👗",
    colors: { primary: "#111827", accent: "#EC4899", dark: "#000000" },
    fonts: { display: "Fraunces", body: "Inter" },
    images: {
      heroQuery: "fashion boutique clothing store interior",
      gallery: [
        "new arrivals fashion rack store",
        "boutique store interior clothing",
        "occasion wear fashion display",
        "personal styling session fashion",
        "fitting room boutique mirror",
        "seasonal fashion collection display",
      ],
    },
    hero: {
      headline: "Style That Speaks For You",
      subheadline: "{{businessName}} brings curated fashion to {{city}} — trend-forward, quality-first, made for every wardrobe.",
      ctaPrimary: "Shop Collection",
      ctaSecondary: "Visit Store",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} curates fashion for people who want to stand out without trying too hard. Quality fabrics, thoughtful design, and pieces that last beyond a season.",
    },
    services: [
      { title: "Everyday Wear", description: "Comfortable, versatile pieces for daily life.", icon: "Shirt" },
      { title: "Occasion Wear", description: "Statement outfits for special moments.", icon: "PartyPopper" },
      { title: "Styling Consultation", description: "Personal styling to match your look.", icon: "Sparkles" },
      { title: "Custom Tailoring", description: "Perfect fit, made just for you.", icon: "Ruler" },
    ],
    features: [
      { title: "Curated Collections", description: "New arrivals dropped every season." },
      { title: "Quality Fabrics", description: "Comfort that lasts wear after wear." },
      { title: "Easy Returns", description: "Hassle-free exchange and returns policy." },
      { title: "Personal Styling", description: "One-on-one styling sessions available." },
    ],
    gallery: ["New Arrivals", "Store Interior", "Occasion Wear", "Styling Session", "Fitting Room", "Seasonal Collection"],
    testimonials: [
      { name: "Ishita V.", role: "Customer", quote: "Every piece I've bought here fits and feels premium.", rating: 5 },
      { name: "Kabir R.", role: "Customer", quote: "The styling session completely changed my wardrobe game.", rating: 5 },
      { name: "Leena F.", role: "Customer", quote: "Quality that actually matches the price tag.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer custom tailoring?", a: "Yes, tailoring services are available for a perfect fit." },
      { q: "What is your return policy?", a: "We offer easy exchanges and returns within a set window — ask in-store." },
      { q: "Do you have seasonal sales?", a: "Yes, seasonal collections and sales run throughout the year." },
      { q: "Do you offer styling consultations?", a: "Yes, book a one-on-one styling session with our team." },
      { q: "Do you stock plus sizes?", a: "Yes, our collections include an extended size range." },
    ],
    cta: { headline: "Refresh Your Wardrobe", button: "Shop Collection" },
  },

  bakery: {
    key: "bakery",
    label: "Bakery",
    emoji: "🍰",
    colors: { primary: "#C2410C", accent: "#FDE68A", dark: "#3B1408" },
    fonts: { display: "Fraunces", body: "Inter" },
    images: {
      heroQuery: "bakery interior fresh bread cakes display",
      gallery: [
        "custom birthday cake decorated",
        "bakery bread counter fresh",
        "pastry display case bakery",
        "baker kneading dough kitchen",
        "dessert table bakery spread",
        "bakery order pickup counter",
      ],
    },
    hero: {
      headline: "Freshly Baked, Made with Love",
      subheadline: "{{businessName}} bakes daily for {{city}} — cakes, breads, and pastries made from scratch, every single day.",
      ctaPrimary: "Order Now",
      ctaSecondary: "View Menu",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} started with a love for baking and a belief that good ingredients make all the difference. Every item is baked fresh, never rushed.",
    },
    services: [
      { title: "Custom Cakes", description: "Designed for birthdays, weddings, and celebrations.", icon: "Cake" },
      { title: "Fresh Breads", description: "Baked daily using traditional methods.", icon: "Croissant" },
      { title: "Pastries & Desserts", description: "A rotating selection of sweet treats.", icon: "IceCreamCone" },
      { title: "Bulk & Event Orders", description: "Catering for parties and corporate events.", icon: "PartyPopper" },
    ],
    features: [
      { title: "Baked Fresh Daily", description: "Nothing sits on the shelf overnight." },
      { title: "Custom Cake Design", description: "Your vision, brought to life in cake form." },
      { title: "Quality Ingredients", description: "No shortcuts, no preservatives." },
      { title: "Same-Day Delivery", description: "Order today, enjoy today." },
    ],
    gallery: ["Custom Cake", "Bread Counter", "Pastry Display", "Baking in Progress", "Dessert Table", "Order Pickup"],
    testimonials: [
      { name: "Sneha D.", role: "Customer", quote: "The custom cake was more beautiful than I imagined.", rating: 5 },
      { name: "Manoj K.", role: "Customer", quote: "Freshest bread I've found anywhere in {{city}}.", rating: 5 },
      { name: "Alisha N.", role: "Customer", quote: "Ordered for a party — everyone asked where it was from.", rating: 5 },
    ],
    faq: [
      { q: "Do you take custom cake orders?", a: "Yes, custom designs can be ordered with advance notice." },
      { q: "How far in advance should I order?", a: "For custom cakes, 2-3 days notice is recommended." },
      { q: "Do you deliver?", a: "Yes, same-day delivery is available across {{city}}." },
      { q: "Do you cater for events?", a: "Yes, bulk and event orders are welcome." },
      { q: "Do you have eggless options?", a: "Yes, eggless versions are available for most items." },
    ],
    cta: { headline: "Something Sweet Awaits", button: "Order Now" },
  },

  sweetshop: {
    key: "sweetshop",
    label: "Sweet Shop",
    emoji: "🍬",
    colors: { primary: "#B91C1C", accent: "#FACC15", dark: "#3B0A0A" },
    fonts: { display: "Poppins", body: "Inter" },
    images: {
      heroQuery: "indian sweets shop mithai counter",
      gallery: [
        "indian sweets counter display",
        "festival gift box sweets",
        "sweet gift hamper packaging",
        "sweet shop kitchen preparation",
        "bulk sweets order tray",
        "sweet shop storefront traditional",
      ],
    },
    hero: {
      headline: "Sweetness, Made the Traditional Way",
      subheadline: "{{businessName}} has been {{city}}'s favorite sweet shop — authentic recipes, fresh daily, festival-ready always.",
      ctaPrimary: "Order Now",
      ctaSecondary: "View Sweets",
    },
    about: {
      title: "Our Story",
      body: "{{businessName}} has kept traditional recipes alive for generations, using pure ingredients and time-tested methods that never change.",
    },
    services: [
      { title: "Traditional Sweets", description: "Classic recipes made fresh daily.", icon: "Candy" },
      { title: "Festival Specials", description: "Curated boxes for every celebration.", icon: "PartyPopper" },
      { title: "Gift Hampers", description: "Beautifully packed gifting options.", icon: "Gift" },
      { title: "Bulk Orders", description: "Catering for weddings and events.", icon: "Package" },
    ],
    features: [
      { title: "Pure Ingredients", description: "No shortcuts, just quality ghee and milk." },
      { title: "Fresh Daily", description: "Made in small batches every day." },
      { title: "Festival Ready", description: "Special collections for every occasion." },
      { title: "Custom Gift Boxes", description: "Personalized packaging available." },
    ],
    gallery: ["Sweet Counter", "Festival Box", "Gift Hamper", "Kitchen", "Bulk Order Prep", "Store Front"],
    testimonials: [
      { name: "Geeta M.", role: "Customer", quote: "Tastes exactly like my grandmother's homemade sweets.", rating: 5 },
      { name: "Ashok V.", role: "Customer", quote: "Our go-to for every festival gift box.", rating: 5 },
      { name: "Ruchi P.", role: "Customer", quote: "Ordered for a wedding — quality and quantity were spot on.", rating: 5 },
    ],
    faq: [
      { q: "Do you take bulk orders for events?", a: "Yes, we cater for weddings, festivals, and corporate events." },
      { q: "Are your sweets made fresh daily?", a: "Yes, everything is prepared in small batches every day." },
      { q: "Do you offer gift packaging?", a: "Yes, custom gift boxes and hampers are available." },
      { q: "Do you use preservatives?", a: "No, our sweets are made fresh without added preservatives." },
      { q: "Can I place an order online?", a: "Yes, orders can be placed directly and picked up or delivered." },
    ],
    cta: { headline: "Celebrate With Something Sweet", button: "Order Now" },
  },

  pharmacy: {
    key: "pharmacy",
    label: "Pharmacy",
    emoji: "💊",
    colors: { primary: "#065F46", accent: "#6EE7B7", dark: "#022C22" },
    fonts: { display: "Inter", body: "Inter" },
    images: {
      heroQuery: "pharmacy store interior medicine shelves",
      gallery: [
        "pharmacy store front modern",
        "medicine counter pharmacy shelves",
        "pharmacy delivery service package",
        "pharmacist consultation desk",
        "wellness aisle pharmacy products",
        "pharmacist at work counter",
      ],
    },
    hero: {
      headline: "Your Health, Delivered Reliably",
      subheadline: "{{businessName}} serves {{city}} with genuine medicines, fast delivery, and pharmacist support you can trust.",
      ctaPrimary: "Order Medicines",
      ctaSecondary: "Find Store",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} has been a trusted neighborhood pharmacy, committed to genuine medication, fair pricing, and reliable service for every customer.",
    },
    services: [
      { title: "Prescription Medicines", description: "Genuine medication, dispensed accurately.", icon: "Pill" },
      { title: "Home Delivery", description: "Fast delivery straight to your door.", icon: "Truck" },
      { title: "Health Products", description: "Wellness and personal care essentials.", icon: "HeartPulse" },
      { title: "Pharmacist Consultation", description: "Expert guidance on medication and dosage.", icon: "Stethoscope" },
    ],
    features: [
      { title: "100% Genuine Medicines", description: "Sourced only from licensed distributors." },
      { title: "Fast Delivery", description: "Same-day delivery across {{city}}." },
      { title: "Licensed Pharmacists", description: "Expert advice available on every visit." },
      { title: "Digital Prescriptions", description: "Upload and order in a few taps." },
    ],
    gallery: ["Store Front", "Medicine Counter", "Delivery Service", "Consultation Desk", "Wellness Aisle", "Pharmacist at Work"],
    testimonials: [
      { name: "Ramesh T.", role: "Customer", quote: "Fast delivery and always genuine medicines.", rating: 5 },
      { name: "Sana Q.", role: "Customer", quote: "The pharmacist took time to explain my prescription clearly.", rating: 5 },
      { name: "Deepa J.", role: "Customer", quote: "Reliable service, never had an issue in years.", rating: 5 },
    ],
    faq: [
      { q: "Do you deliver medicines?", a: "Yes, same-day delivery is available across {{city}}." },
      { q: "Can I order with a digital prescription?", a: "Yes, simply upload your prescription when ordering." },
      { q: "Are your medicines genuine?", a: "Yes, we source exclusively from licensed distributors." },
      { q: "Do you stock wellness products?", a: "Yes, a full range of health and personal care items is available." },
      { q: "Can I consult a pharmacist?", a: "Yes, our licensed pharmacists are available for guidance." },
    ],
    cta: { headline: "Get Your Medicines Delivered", button: "Order Medicines" },
  },

  petstore: {
    key: "petstore",
    label: "Pet Store",
    emoji: "🐶",
    colors: { primary: "#92400E", accent: "#86EFAC", dark: "#2E1505" },
    fonts: { display: "Poppins", body: "Inter" },
    images: {
      heroQuery: "pet store interior dog cat supplies",
      gallery: [
        "dog grooming session pet store",
        "pet food aisle store shelves",
        "vet checkup dog cat clinic",
        "pet boarding area comfortable",
        "pet store front entrance",
        "happy pet owner customer store",
      ],
    },
    hero: {
      headline: "Everything Your Pet Needs, in One Place",
      subheadline: "{{businessName}} keeps {{city}}'s pets happy and healthy — food, grooming, and expert care under one roof.",
      ctaPrimary: "Shop Now",
      ctaSecondary: "Book Grooming",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} was built by pet lovers, for pet lovers. From premium nutrition to grooming and care, we treat every pet like family.",
    },
    services: [
      { title: "Pet Food & Supplies", description: "Premium nutrition and accessories.", icon: "Bone" },
      { title: "Grooming Services", description: "Professional grooming for every breed.", icon: "Scissors" },
      { title: "Veterinary Care", description: "Health checkups and vaccinations.", icon: "Stethoscope" },
      { title: "Pet Boarding", description: "Safe, comfortable stays while you're away.", icon: "Home" },
    ],
    features: [
      { title: "Premium Brands", description: "Trusted pet food and product brands." },
      { title: "Certified Groomers", description: "Gentle, professional grooming care." },
      { title: "In-house Vet Support", description: "Health checks without an extra trip." },
      { title: "Loyalty Program", description: "Rewards for every visit." },
    ],
    gallery: ["Grooming Session", "Pet Food Aisle", "Vet Checkup", "Boarding Area", "Store Front", "Happy Customer"],
    testimonials: [
      { name: "Anusha B.", role: "Pet Parent", quote: "My dog actually enjoys grooming day now!", rating: 5 },
      { name: "Vishal N.", role: "Pet Parent", quote: "Great range of food brands and honest advice on nutrition.", rating: 5 },
      { name: "Kritika S.", role: "Pet Parent", quote: "Boarded my cat here for a week — came back happy and healthy.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer grooming services?", a: "Yes, professional grooming is available for all breeds." },
      { q: "Do you have a resident veterinarian?", a: "Yes, veterinary checkups and vaccinations are available in-house." },
      { q: "Can I board my pet here?", a: "Yes, safe and comfortable boarding is available." },
      { q: "Do you sell prescription pet food?", a: "Yes, we stock both regular and prescription diets." },
      { q: "Do you offer a loyalty program?", a: "Yes, earn rewards with every purchase or visit." },
    ],
    cta: { headline: "Give Your Pet the Best", button: "Shop Now" },
  },

  travelagency: {
    key: "travelagency",
    label: "Travel Agency",
    emoji: "✈️",
    colors: { primary: "#0369A1", accent: "#FDBA74", dark: "#02243B" },
    fonts: { display: "Poppins", body: "Inter" },
    images: {
      heroQuery: "travel agency vacation destination scenic",
      gallery: [
        "beach destination vacation travel",
        "mountain getaway scenic travel",
        "city tour travel destination",
        "traveler client trip photo",
        "travel agency office consultation",
        "travel itinerary planning desk",
      ],
    },
    hero: {
      headline: "Your Next Adventure Starts Here",
      subheadline: "{{businessName}} plans unforgettable trips for {{city}} travelers — seamless bookings, curated itineraries, real support.",
      ctaPrimary: "Plan My Trip",
      ctaSecondary: "View Packages",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} has helped travelers from {{city}} explore the world with confidence — from quick getaways to bucket-list adventures.",
    },
    services: [
      { title: "Holiday Packages", description: "Curated trips to top destinations.", icon: "Plane" },
      { title: "Flight & Hotel Booking", description: "Best deals, booked in minutes.", icon: "Ticket" },
      { title: "Visa Assistance", description: "Guided support through visa paperwork.", icon: "FileCheck" },
      { title: "Custom Itineraries", description: "Trips planned around your interests.", icon: "MapPin" },
    ],
    features: [
      { title: "Curated Packages", description: "Handpicked destinations and experiences." },
      { title: "24/7 Travel Support", description: "Help whenever you need it, wherever you are." },
      { title: "Best Price Guarantee", description: "Competitive pricing on every booking." },
      { title: "Visa & Documentation", description: "Complete support through the paperwork." },
    ],
    gallery: ["Beach Destination", "Mountain Getaway", "City Tour", "Client Trip", "Office Consultation", "Travel Planning"],
    testimonials: [
      { name: "Nisha R.", role: "Traveler", quote: "Planned our honeymoon perfectly, down to the smallest detail.", rating: 5 },
      { name: "Gaurav M.", role: "Traveler", quote: "Visa process was smooth thanks to their support.", rating: 5 },
      { name: "Priya L.", role: "Traveler", quote: "Best prices I found for our family trip.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer custom itineraries?", a: "Yes, trips can be fully customized to your preferences." },
      { q: "Do you assist with visa applications?", a: "Yes, we guide you through the entire visa process." },
      { q: "Can you book flights and hotels together?", a: "Yes, we handle complete travel bookings in one place." },
      { q: "Do you offer group travel packages?", a: "Yes, group and family packages are available." },
      { q: "Is travel insurance included?", a: "Travel insurance can be added to any package on request." },
    ],
    cta: { headline: "Let's Plan Your Getaway", button: "Plan My Trip" },
  },

  photography: {
    key: "photography",
    label: "Photography",
    emoji: "📸",
    colors: { primary: "#18181B", accent: "#F43F5E", dark: "#000000" },
    fonts: { display: "Fraunces", body: "Inter" },
    images: {
      heroQuery: "photography studio camera equipment professional",
      gallery: [
        "wedding photography couple shoot",
        "portrait photography session studio",
        "event photography coverage camera",
        "behind the scenes photoshoot",
        "photography studio setup lighting",
        "photo album design layout",
      ],
    },
    hero: {
      headline: "Moments, Captured Beautifully",
      subheadline: "{{businessName}} tells your story through the lens — weddings, portraits, and events across {{city}}.",
      ctaPrimary: "Book a Shoot",
      ctaSecondary: "View Portfolio",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} believes every moment deserves to be remembered beautifully. With an eye for detail and a passion for storytelling, we capture what matters.",
    },
    services: [
      { title: "Wedding Photography", description: "Complete coverage of your big day.", icon: "Camera" },
      { title: "Portrait Sessions", description: "Professional portraits for individuals and families.", icon: "Aperture" },
      { title: "Event Coverage", description: "Corporate and social event photography.", icon: "PartyPopper" },
      { title: "Photo Editing", description: "Professional retouching and album design.", icon: "Image" },
    ],
    features: [
      { title: "Experienced Photographers", description: "Years of experience across genres." },
      { title: "Cinematic Editing", description: "Photos that feel like art." },
      { title: "Fast Turnaround", description: "Edited galleries delivered promptly." },
      { title: "Custom Packages", description: "Pricing tailored to your event." },
    ],
    gallery: ["Wedding Shoot", "Portrait Session", "Event Coverage", "Behind the Scenes", "Studio Setup", "Album Design"],
    testimonials: [
      { name: "Ayesha T.", role: "Bride", quote: "Our wedding photos are better than we could have imagined.", rating: 5 },
      { name: "Rajat K.", role: "Client", quote: "Captured our corporate event perfectly, on time and professional.", rating: 5 },
      { name: "Neel V.", role: "Client", quote: "The portrait session felt effortless and the results were stunning.", rating: 5 },
    ],
    faq: [
      { q: "Do you cover weddings outside {{city}}?", a: "Yes, we travel for destination weddings and events." },
      { q: "How long until I receive my photos?", a: "Edited galleries are typically delivered within a few weeks." },
      { q: "Do you offer videography as well?", a: "Yes, video coverage can be added to most packages." },
      { q: "Can I customize my package?", a: "Yes, packages are tailored to your event's specific needs." },
      { q: "Do you provide printed albums?", a: "Yes, custom album design and printing is available." },
    ],
    cta: { headline: "Let's Capture Something Beautiful", button: "Book a Shoot" },
  },

  construction: {
    key: "construction",
    label: "Construction",
    emoji: "🏗️",
    colors: { primary: "#78350F", accent: "#FACC15", dark: "#2A1204" },
    fonts: { display: "Archivo Black", body: "Inter" },
    images: {
      heroQuery: "construction site building crane work",
      gallery: [
        "construction site progress workers",
        "completed building project exterior",
        "construction team on site work",
        "blueprint review construction plan",
        "construction material selection site",
        "building handover day construction",
      ],
    },
    hero: {
      headline: "Building {{city}}, One Project at a Time",
      subheadline: "{{businessName}} delivers reliable, high-quality construction — residential, commercial, and everything between.",
      ctaPrimary: "Get a Quote",
      ctaSecondary: "View Projects",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} has built a reputation for quality construction and on-time delivery across {{city}}. We manage every project with precision and accountability.",
    },
    services: [
      { title: "Residential Construction", description: "Homes built to last, designed to inspire.", icon: "Home" },
      { title: "Commercial Projects", description: "Offices and retail spaces built for business.", icon: "Building2" },
      { title: "Renovation & Remodeling", description: "Transforming existing spaces with quality work.", icon: "Hammer" },
      { title: "Project Management", description: "End-to-end oversight from design to delivery.", icon: "ClipboardCheck" },
    ],
    features: [
      { title: "On-Time Delivery", description: "Projects completed within committed timelines." },
      { title: "Quality Materials", description: "No compromises on structural integrity." },
      { title: "Experienced Team", description: "Skilled engineers and site supervisors." },
      { title: "Transparent Costing", description: "Clear estimates, no hidden costs." },
    ],
    gallery: ["Site in Progress", "Completed Project", "Team on Site", "Blueprint Review", "Material Selection", "Handover Day"],
    testimonials: [
      { name: "Vinay P.", role: "Client", quote: "Delivered our home exactly on schedule and on budget.", rating: 5 },
      { name: "Reshma A.", role: "Client", quote: "Quality of work was excellent, no shortcuts taken.", rating: 5 },
      { name: "Alok S.", role: "Business Owner", quote: "Managed our office build with real professionalism.", rating: 5 },
    ],
    faq: [
      { q: "Do you handle both residential and commercial projects?", a: "Yes, we manage projects across both categories." },
      { q: "How do you estimate project costs?", a: "We provide a detailed, transparent estimate before work begins." },
      { q: "Do you manage permits and approvals?", a: "Yes, our team handles necessary approvals as part of project management." },
      { q: "What is your typical project timeline?", a: "Timelines vary by scope and are shared upfront during planning." },
      { q: "Do you offer renovation services?", a: "Yes, remodeling and renovation are part of our core services." },
    ],
    cta: { headline: "Let's Build Something Great", button: "Get a Quote" },
  },

  interiordesign: {
    key: "interiordesign",
    label: "Interior Design",
    emoji: "🛋️",
    colors: { primary: "#3F3D56", accent: "#E8C07D", dark: "#191826" },
    fonts: { display: "Fraunces", body: "Inter" },
    images: {
      heroQuery: "modern interior design living room styled",
      gallery: [
        "living room interior design styled",
        "modular kitchen design modern",
        "office interior design workspace",
        "3d render interior design concept",
        "before after interior renovation",
        "site execution interior design work",
      ],
    },
    hero: {
      headline: "Spaces Designed Around You",
      subheadline: "{{businessName}} transforms homes and offices across {{city}} into spaces that feel truly yours.",
      ctaPrimary: "Book a Consultation",
      ctaSecondary: "View Portfolio",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} designs interiors that balance beauty and function. Every project starts with understanding how you actually live and work.",
    },
    services: [
      { title: "Home Interiors", description: "Full-home design from concept to completion.", icon: "Home" },
      { title: "Office Interiors", description: "Workspaces designed for productivity and style.", icon: "Building2" },
      { title: "Modular Kitchens", description: "Smart, beautiful kitchen design.", icon: "ChefHat" },
      { title: "Space Planning", description: "Layouts optimized for how you live.", icon: "Ruler" },
    ],
    features: [
      { title: "Personalized Design", description: "Every project shaped around your lifestyle." },
      { title: "3D Visualization", description: "See your space before it's built." },
      { title: "End-to-End Execution", description: "From design to final handover." },
      { title: "Quality Craftsmanship", description: "Trusted vendors and skilled execution teams." },
    ],
    gallery: ["Living Room Design", "Modular Kitchen", "Office Space", "3D Render", "Before & After", "Site Execution"],
    testimonials: [
      { name: "Aarti G.", role: "Client", quote: "Our home finally feels like us. Couldn't be happier.", rating: 5 },
      { name: "Sandeep R.", role: "Client", quote: "The 3D visuals matched the final result almost exactly.", rating: 5 },
      { name: "Fiona D.", role: "Client", quote: "Handled our office redesign with real attention to detail.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer 3D visualization?", a: "Yes, 3D renders are provided before execution begins." },
      { q: "Do you handle both homes and offices?", a: "Yes, we design residential and commercial interiors." },
      { q: "What is the typical project timeline?", a: "Timelines depend on scope and are shared during consultation." },
      { q: "Do you manage execution as well?", a: "Yes, we offer end-to-end design and execution." },
      { q: "How do I get started?", a: "Book a consultation and our design team will take it from there." },
    ],
    cta: { headline: "Let's Design Your Space", button: "Book a Consultation" },
  },

  homeservices: {
    key: "homeservices",
    label: "Home Services",
    emoji: "🔧",
    colors: { primary: "#1D4ED8", accent: "#FBBF24", dark: "#0B1B4D" },
    fonts: { display: "Poppins", body: "Inter" },
    images: {
      heroQuery: "home repair technician toolbox service",
      gallery: [
        "technician at work home repair",
        "before after home repair fix",
        "service van technician arriving",
        "technician customer home visit",
        "toolkit home repair equipment",
        "completed home repair job",
      ],
    },
    hero: {
      headline: "Reliable Help, Right When You Need It",
      subheadline: "{{businessName}} connects {{city}} homes with trusted, verified professionals for every repair and service.",
      ctaPrimary: "Book a Service",
      ctaSecondary: "View Services",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} was built to make home services simple — verified professionals, fair pricing, and work you can trust.",
    },
    services: [
      { title: "Repairs & Maintenance", description: "Quick fixes for everyday home issues.", icon: "Wrench" },
      { title: "Cleaning Services", description: "Deep cleaning for homes and offices.", icon: "SprayCan" },
      { title: "Appliance Installation", description: "Safe, professional setup for new appliances.", icon: "Plug" },
      { title: "Emergency Support", description: "Fast response for urgent issues.", icon: "Siren" },
    ],
    features: [
      { title: "Verified Professionals", description: "Every technician background-checked." },
      { title: "Transparent Pricing", description: "Upfront quotes, no surprises." },
      { title: "Same-Day Service", description: "Fast response for urgent needs." },
      { title: "Service Guarantee", description: "Work backed by our satisfaction promise." },
    ],
    gallery: ["Technician at Work", "Before & After", "Service Van", "Customer Home", "Tool Kit", "Completed Job"],
    testimonials: [
      { name: "Om Prakash", role: "Customer", quote: "Fixed my plumbing issue the same day I called.", rating: 5 },
      { name: "Charu M.", role: "Customer", quote: "Professional, punctual, and fairly priced.", rating: 5 },
      { name: "Vishesh A.", role: "Customer", quote: "Great cleaning service, will book again.", rating: 5 },
    ],
    faq: [
      { q: "How quickly can a technician arrive?", a: "Most services offer same-day or next-day appointments." },
      { q: "Are your professionals verified?", a: "Yes, every technician is background-checked before onboarding." },
      { q: "Do you offer emergency services?", a: "Yes, urgent requests are prioritized for fast response." },
      { q: "How is pricing determined?", a: "You'll receive a transparent quote before any work begins." },
      { q: "Is there a service guarantee?", a: "Yes, all work is backed by our satisfaction guarantee." },
    ],
    cta: { headline: "Get It Fixed Today", button: "Book a Service" },
  },

  electrician: {
    key: "electrician",
    label: "Electrician",
    emoji: "⚡",
    colors: { primary: "#78350F", accent: "#FDE047", dark: "#221000" },
    fonts: { display: "Archivo Black", body: "Inter" },
    images: {
      heroQuery: "electrician working panel wiring safety",
      gallery: [
        "electrician at work wiring panel",
        "electrical wiring job closeup",
        "circuit panel upgrade electrician",
        "electrician service van parked",
        "electrical safety check inspection",
        "completed electrical installation panel",
      ],
    },
    hero: {
      headline: "Safe, Certified Electrical Work",
      subheadline: "{{businessName}} handles wiring, repairs, and installations across {{city}} — safe, licensed, reliable.",
      ctaPrimary: "Book a Visit",
      ctaSecondary: "View Services",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} brings licensed electrical expertise to every home and business in {{city}}. Safety and reliability come first, always.",
    },
    services: [
      { title: "Wiring & Rewiring", description: "Safe, code-compliant electrical wiring.", icon: "Zap" },
      { title: "Repairs & Troubleshooting", description: "Fast diagnosis and fixes for electrical issues.", icon: "Wrench" },
      { title: "Appliance Installation", description: "Safe setup for major home appliances.", icon: "Plug" },
      { title: "Emergency Service", description: "Rapid response for urgent electrical issues.", icon: "Siren" },
    ],
    features: [
      { title: "Licensed Electricians", description: "Certified and fully insured technicians." },
      { title: "Same-Day Service", description: "Fast response for most requests." },
      { title: "Upfront Pricing", description: "Know the cost before work begins." },
      { title: "Safety First", description: "All work meets current safety codes." },
    ],
    gallery: ["Electrician at Work", "Wiring Job", "Panel Upgrade", "Service Van", "Safety Check", "Completed Installation"],
    testimonials: [
      { name: "Manjeet S.", role: "Customer", quote: "Fixed a tricky wiring issue quickly and safely.", rating: 5 },
      { name: "Preeti L.", role: "Customer", quote: "Arrived on time and explained everything clearly.", rating: 5 },
      { name: "Yash G.", role: "Customer", quote: "Fair pricing and genuinely careful work.", rating: 5 },
    ],
    faq: [
      { q: "Are you licensed and insured?", a: "Yes, all our electricians are licensed and fully insured." },
      { q: "Do you offer emergency callouts?", a: "Yes, emergency electrical service is available." },
      { q: "How is pricing determined?", a: "You'll get an upfront quote before any work starts." },
      { q: "Do you handle commercial electrical work?", a: "Yes, we service both residential and commercial properties." },
      { q: "Can you upgrade old wiring?", a: "Yes, rewiring and panel upgrades are part of our core services." },
    ],
    cta: { headline: "Get Your Electrical Issue Fixed", button: "Book a Visit" },
  },

  plumber: {
    key: "plumber",
    label: "Plumber",
    emoji: "🚰",
    colors: { primary: "#0C4A6E", accent: "#7DD3FC", dark: "#03202F" },
    fonts: { display: "Poppins", body: "Inter" },
    images: {
      heroQuery: "plumber fixing pipes wrench repair",
      gallery: [
        "plumber fixing pipes wrench",
        "pipe installation plumbing work",
        "leak repair plumber closeup",
        "plumber service van parked",
        "bathroom pipe fitting plumber",
        "completed plumbing job pipes",
      ],
    },
    hero: {
      headline: "Fast, Reliable Plumbing You Can Trust",
      subheadline: "{{businessName}} solves plumbing problems across {{city}} — leaks, installs, and emergencies handled fast.",
      ctaPrimary: "Book a Visit",
      ctaSecondary: "View Services",
    },
    about: {
      title: "About Us",
      body: "{{businessName}} has been fixing {{city}}'s plumbing issues with honest pricing and dependable work. No job too small, no fix left half-done.",
    },
    services: [
      { title: "Leak Repairs", description: "Fast fixes for leaks big and small.", icon: "Droplet" },
      { title: "Pipe Installation", description: "New installations done right the first time.", icon: "Wrench" },
      { title: "Drain Cleaning", description: "Clear clogs fast, without the mess.", icon: "Waves" },
      { title: "Emergency Plumbing", description: "Rapid response for urgent issues.", icon: "Siren" },
    ],
    features: [
      { title: "Licensed Plumbers", description: "Trained, background-checked professionals." },
      { title: "Same-Day Response", description: "Fast callouts for urgent problems." },
      { title: "Upfront Quotes", description: "No surprises on the final bill." },
      { title: "Clean Workmanship", description: "We leave your space as tidy as we found it." },
    ],
    gallery: ["Plumber at Work", "Pipe Installation", "Leak Repair", "Service Van", "Bathroom Fitting", "Completed Job"],
    testimonials: [
      { name: "Harpreet K.", role: "Customer", quote: "Fixed a major leak fast, no mess left behind.", rating: 5 },
      { name: "Ajay N.", role: "Customer", quote: "Honest pricing, showed up exactly on time.", rating: 5 },
      { name: "Bhavya R.", role: "Customer", quote: "Solved a drainage issue others couldn't figure out.", rating: 5 },
    ],
    faq: [
      { q: "Do you offer emergency plumbing?", a: "Yes, urgent requests are handled with priority response." },
      { q: "How is pricing determined?", a: "You'll receive an upfront quote before work begins." },
      { q: "Do you handle bathroom installations?", a: "Yes, full bathroom fittings and installations are part of our services." },
      { q: "Are your plumbers licensed?", a: "Yes, all our plumbers are trained and background-checked." },
      { q: "Do you offer drain cleaning?", a: "Yes, we clear clogs and blockages quickly and thoroughly." },
    ],
    cta: { headline: "Get Your Plumbing Fixed Today", button: "Book a Visit" },
  },
};

export default categories;
export const categoryKeys = Object.keys(categories);